### PR TITLE
[MSKINS-193] remove loading 3rd party resources for Google site search

### PR DESCRIPTION
**Pull request by kwin**
use simple placeholder
remove JS loaded from Google

### CODE REVIEW

**Comment by michael-o** [comment]
Will take care of this.

**Comment by stevecrox** [comment]
Could I ask the thinking behind the change?

The facebook, pwiki and google analytic options all require external resources to function and even if those resources were bundled with the skin the functionality for social media and google parts require internet access to work.

The css here references a CDN resource which should be cached by the browser so should mean it loads quickly.

Which has me struggling to understand your motivation.

**Comment by kwin** [comment]
The reasoning is outlined in https://issues.apache.org/jira/browse/MSKINS-193. In short "Google must not collect data about a visitor of a site generated by maven-fluido-skin". As you can see in this PR, the external resources have been removed completely (which is even faster than delivering it from any CDN :-))

**Comment by stevecrox** [comment]
That is not something I thought of.

For me this builds, the search box remains in the topbar and sidebar and looks fine. The search functionality still works in both versions.

**Comment by kwin** [comment]
@michael-o Any chance you can look at this and the PR for MSKINS-194?

**Comment by michael-o** [comment]
This is something I will definitively process after I finish Doxia Sitetools 2.0.0-M3 vote. This is not forgotten.

**Comment by jira-importer** [comment]
Resolve #282

**Pull request closed without merging**
