### PR TITLE
[MSKINS-104] Remove obsolete meta tags

### PR DESCRIPTION
**Pull request by mikemol1991**
Submitted by: Mike Mol

**I removed the obsolete Meta tag for ```Content-Language```.**

Following this checklist to help us incorporate your
contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/MSKINS) filed
for the change (usually before you start working on it). Trivial changes like typos do not
require a JIRA issue. Your pull request should address just this issue, without
pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Format the pull request title like ```[MSKINS-XXX] - Fixes bug in ApproximateQuantiles```,
where you replace ```MSKINS-XXX``` with the appropriate JIRA issue. Best practice
is to use the JIRA issue title in the pull request title and in the first line of the
commit message.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run mvn clean verify to make sure basic checks pass. A more thorough check will
be performed on your pull request automatically.
- [x] You have run the [Core IT](https://maven.apache.org/core-its/core-it-suite/) successfully.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licenced under the Apache License Version 2.0, January 2004

### CODE REVIEW

**Comment by slachiewicz** [comment]
This was just removal of language attribute but we should add lang in root html tag 

see: https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by mikemol1991** [comment]
@slachiewicz as you can see the lang is already set, but only when _$locale_ is filled. Is this what you mean or do you want a default value?

`<html xmlns="http://www.w3.org/1999/xhtml"#if ( $locale ) xml:lang="$locale.language" lang="$locale.language"#end>`

**Comment by slachiewicz** [comment]
sorry, you’re right. I missed  that part. Thx!

**Comment by jira-importer** [comment]
Resolve #153

**Pull request merged**
