### PR TITLE
[MSKINS-234] Disabling 'topBarEnabled' doesn't remove padding

### PR DESCRIPTION
**Pull request by michael-o**
This closes #53

### CODE REVIEW

**Comment by michael-o** [comment]
Alternatively, this top padding would be added to the `<header>` element containing `<div id="banner">`.

**Comment by michael-o** [comment]
@notmyfault, have a look.

**Review by NotMyFault — APPROVED** [review]
Thanks a lot!

Are there plans to backport this to the 1.x branch?

**Comment by michael-o** [comment]
> Thanks a lot!
> 
> Are there plans to backport this to the 1.x branch?

Yes, I have back ported several issues from master to 1.x already. This will be the last issue for 1.12.0.

**Comment by NotMyFault** [comment]
> > Thanks a lot!
> > Are there plans to backport this to the 1.x branch?
> 
> Yes, I have back ported several issues from master to 1.x already. This will be the last issue for 1.12.0.

Awesome! Updating to maven-site-plugin 4.x is no blocker on our end, so either works out 🚀

**Comment by jira-importer** [comment]
Resolve #232

**Pull request merged**
