### PR TITLE
MSKINS-137 Make the hamburger menu work with the top-navigation ena…

### PR DESCRIPTION
**Pull request by joshelser**
…bled and sidebar-navigation disabled

Original work done in https://github.com/apache/maven-skins/pull/4/commits/f559695b03826158eb302e60b40d4924f28a8bf4
by Misty.

### CODE REVIEW

**Comment by joshelser** [comment]
Old (unsubmitted) PR was apache/maven-skins#4 for those interested in the lineage.

**Comment by hboutemy** [comment]
Hi Josh,

Thank you for your help: I'm very interested to merge.
But I don't understand what this change does: can you describe a little bit the issue (what a "hamburger menu" is)? Is there one existing IT that show clearly the issue (then the fix)?

Sidenote: this is a generic topic with Skins, ie understanding html/css changes. Any generic idea on how to describe an issue and a fix, between "designer oriented" people (who are html/css experts) and "java dev" oriented people (like Maven developpers, like me, who is not proficient at all with modern html/css, who need to judge before merging...)

**Comment by joshelser** [comment]
Thanks, Hervé!

> But I don't understand what this change does: can you describe a little bit the issue (what a "hamburger menu" is)?

See https://en.wikipedia.org/wiki/Hamburger_button for starters :). If you visit https://hbase.apache.org/ on your mobile or shrink down the page in a browser, you'll see the nav-bar at the top of the page convert into a drop-down with the "stacked-lines" (hamburger) button to open/close it.

>  Is there one existing IT that show clearly the issue (then the fix)?

Admittedly, I didn't look at all into how to test :D. Have any pointers/docs/suggestions on what kind of test would be effective?

> Sidenote: this is a generic topic with Skins, ie understanding html/css changes. Any generic idea on how to describe an issue and a fix, between "designer oriented" people (who are html/css experts) and "java dev" oriented people (like Maven developpers, like me, who is not proficient at all with modern html/css, who need to judge before merging...)

Ditto. CSS has changed drastically since I've done anything of consequence with it :D. I'm mostly repurposing Misty's original commit here. My general understanding is that bootstrap is doing some special logic when the "window" (or maybe screen is more appropriate) reduces to a certain size. Then it uses some CSS rules to convert the content into the dynamic drop-down instead of how it appears on screens with adequate width.

**Comment by hboutemy** [comment]
thanks fo the explanation: now I know what a hamburger menu is :)
To test, I understand that any rendering of the skin with a nav bar in a little screen should be used: we already have a few when running "mvn -Prun-its verify"
Then I checked hbase site: the hamburger menu was perfect. But with the patch applied, there is a space added before the topbar: to me, the patch breaks topbar positionning.

Please share a screenshot of the issue you get in hbase, then the result once the patch fixes the issue

**Comment by joshelser** [comment]
>  To test, I understand that any rendering of the skin with a nav bar in a little screen should be used: we already have a few when running "mvn -Prun-its verify"

Great. Will take a look.

> But with the patch applied, there is a space added before the topbar: to me, the patch breaks topbar positionning.

Yeah, I did have to tweak some CSS down in HBase. I assumed that was something we were doing down there -- will have to circle around and see if I can make the equivalent change here instead :)

> Please share a screenshot of the issue you get in hbase, then the result once the patch fixes the issue

Acknowledged.

**Comment by michael-o** [comment]
Is this one still valid?

**Comment by busbey** [comment]
yes, still valid. the Apache HBase project continues to work to maintain a fork of the maven-fluido-skin project entirely due to our need for this one change.

**Comment by michael-o** [comment]
Cam someone rebase this? I will review and merge then.

**Comment by joshelser** [comment]
Let me try to do that today.

**Comment by jira-importer** [comment]
Resolve #159

**Pull request closed without merging**
