### PR TITLE
[MSKINS-167] Add deep anchors to headers

### LINKED ISSUE #167: [MSKINS-114] Update skins footer handling once DOXIASITETOOLS-82 has been published
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MSKINS-114](https://issues.apache.org/jira/browse/MSKINS-114?redirect=false)** and commented

Documenation for /body/footer says:

> If present, the contained text will be used instead of the generated copyright text.

The [default skin](https://svn.apache.org/repos/asf/maven/doxia/doxia-sitetools/trunk/doxia-site-renderer/src/main/resources/org/apache/maven/doxia/siterenderer/resources/default-site.vm) does this correctly with:

```
<div id="footer">
      <div class="xright">
      #if($decoration.body.footer)
        $decoration.body.footer
      #else
        Copyright &#169;#copyright()All Rights Reserved.#publishDate( "bottom" $decoration.publishDate $decoration.version )
      #end
      </div>
      <div class="clear">
        <hr/>
      </div>
```

This logic should be applied here as soon as the Decoration Model 1.7 is released.

Moreover all `site.xml` files and documentation need to be updated.

---

**Affects:** default-1.1, fluido-1.4

This issue is a sub-task of [MSKINS-120](https://issues.apache.org/jira/browse/MSKINS-120)

**Issue Links:**
- [DOXIASITETOOLS-82](https://issues.apache.org/jira/browse/DOXIASITETOOLS-82) Decoration model body/footer type mismatch
 (_**"depends upon"**_)

**Backported to:** [fluido-1.5](https://github.com/apache/maven-fluido-skin/milestone/11?closed=1)

### PR DESCRIPTION
**Pull request by dialaya**
Hi,
This pull add a use of AnchorJS utility to generate deep anchors to sections header

The Permalink icon is displayed on Mouse-Over.
This helps on sharing links.

This closes #167

### CODE REVIEW

**Comment by hboutemy** [comment]
thank you @dialaya , that's really an awesome improvement

**Comment by michael-o** [comment]
This should have been distributed with the site resources and not loaded from the Internet. Just like we do with Bootstrap and other resources.

**Comment by hboutemy** [comment]
@dialaya can you have a look please to host the lib in the skin instead of using CDN, please?

**Comment by hboutemy** [comment]
@dialaya FYI, I just upgraded the skin used by Maven site itself, the result is great https://maven.apache.org/ :)

**Comment by dialaya** [comment]
Hi,

Yes I can do.
I will do.

Thank you.
Regards,

Le lun. 20 avr. 2020 à 00:44, Hervé Boutemy <notifications@github.com> a
écrit :

**Pull request merged**
