### PR TITLE
[MSKINS-157] Fix footer formatting changes in 1.8

### PR DESCRIPTION
**Pull request by twogee**
(introduced by MSKINS-148 and MSKINS-149)

### CODE REVIEW

**Comment by michael-o** [comment]
Looking into...

**Comment by twogee** [comment]
Thanks, could you please share some insights about the roadmap to 2.0?

**Comment by michael-o** [comment]
I don't have any. We'd like to move to newer Bootstrap version, but lack time.

**Comment by jira-importer** [comment]
Resolve #243

**Pull request closed without merging**
