### PR TITLE
MSKINS-145 remove googlePlus code from skins

### PR DESCRIPTION
**Pull request by barclay-reg**
Removed from template, tests, documentation and own skin

### CODE REVIEW

**Comment by slachiewicz** [comment]
Could You completely remove MSKINS-34 ITs as no longer valid (also from pom.xml and ITS.apt files)?

**Comment by barclay-reg** [comment]
@slachiewicz done - didn't realised, that the ITs folder names reference a (requirement) issue

**Comment by slachiewicz** [comment]
Great! Thank You, code merged.

**Comment by jira-importer** [comment]
Resolve #196

**Pull request closed without merging**
