### PR TITLE
[MSKINS-226] Add custom option to explicitly enable AnchorJS along with options

### PR DESCRIPTION
**Pull request by michael-o**
This closes #51

### CODE REVIEW

**Comment by hboutemy** [comment]
having an option to disable, why not, but please enable by default: what is the issue with these (visual) anchors added in https://issues.apache.org/jira/browse/MSKINS-167?

**Comment by michael-o** [comment]
> having an option to disable, why not, but please enable by default: what is the issue with these (visual) anchors added in https://issues.apache.org/jira/browse/MSKINS-167?

None, though consider that all other extra components are disabled by default, maybe not everyone wants it and how to disable if enabled by default?

**Comment by michael-o** [comment]
> > having an option to disable, why not, but please enable by default: what is the issue with these (visual) anchors added in https://issues.apache.org/jira/browse/MSKINS-167?
> 
> Why I didn't enable it by default: consistency with the rest. That is:
> 
>     * Other extras aren't enable by default
> 
>     * None of the others have an explicit enable/disable flag, this would require one
> 
>     * Not everyone wants to have it

@hboutemy @slawekjaranowski Please let me know what you think regarding this.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
Will be better disable it ... generated anchors ids are not the same as doxia generate

**Comment by slachiewicz** [comment]
If we have working Doxia, why we need also js generated?

**Comment by michael-o** [comment]
> If we have working Doxia, why we need also js generated?

Doxia does not generate any IDs by default, you have to request it in the markup. If Doxia would generate them by default, it might lead to duplicate IDs. See [here](https://issues.apache.org/jira/browse/DOXIASITETOOLS-266) for details.

**Comment by michael-o** [comment]
@hboutemy I will first apply the AnchorJS upgrade separately. As said, there is no way to explicitly disable this just like with other options and the inconsistency between AnchorJS IDs and Doxia IDs remains. I will leave this open for now. I still think that this is the right way since any other feature has to be enabled explicitly. This shouldn't be any different.

**Comment by hboutemy** [comment]
I don't understand the whole discussion about generated ids: do we care about it?

the objective is the deep anchors = the "Basic Link" in https://www.bryanbraun.com/anchorjs/
which makes sharing pointers to precise points in documentation easier

this PR makes whole things more complex: do you have any concrete issue with the current links we have in many Doxia generated sites since a few years that you want to disable it by default?

one solution to enable by default but be able to disable could be:
```
  <custom>
    <fluidoSkin>
      <anchorJs>
        <disable>true</disable>
      </anchorJs>
    </fluidoSkin>
  </custom>
```

**Comment by michael-o** [comment]
Yes, problem is TOC macro for example. People assume that the refs in the TOC use the same id as generated by anchorjs which is not true. In fact, this skins knows nothing about Doxia. They are completely disjoint. I will need to add a note that these IDs do not correspond with Doxia IDs. Adding `<disabled>` is possible, but would make it inconsistent with other options.

Ref:
* https://issues.apache.org/jira/browse/DOXIA-696

**Comment by michael-o** [comment]
Branch rebased and I still consider this reasonable to include in the next major for consistency reasons with the other custom options.

**Review by slachiewicz — APPROVED** [review]

**Comment by michael-o** [comment]
@hboutemy We have auto TOC now by @kwin done with Doxia.

**Comment by jira-importer** [comment]
Resolve #284

**Pull request merged**
