### PR TITLE
[MSKINS-246] Upgrade plugins and components (in ITs)

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
This supersedes #58.

**Comment by kwin** [comment]
#58 references a different JIRA ticket

**Comment by michael-o** [comment]
> #58 references a different JIRA ticket. Please split up in two separate commits each referencing different JIRA IDs

Alright, will do.

**Comment by michael-o** [comment]
@kwin done

**Comment by kwin** [comment]
@michael-o I still see only one commit referencing a single JIRA...

**Review by kwin — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #262

**Pull request merged**
